// Code generated by templ - DO NOT EDIT.

package hotreload

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HotReloader() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if DevEnabled() {
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t\t\t(() => {\n\t\t\t\tconst wsURL = (location.protocol === \"https:\" ? \"wss://\" : \"ws://\") + location.host + \"/ws\";\n\t\t\t\tlet connected = false;\n\n\t\t\t\tconst waitForServer = async () => {\n\t\t\t\t\ttry {\n\t\t\t\t\t\tconst res = await fetch(\"/health\");\n\t\t\t\t\t\tif (!res.ok) throw new Error(\"unhealthy\");\n\t\t\t\t\t\tlocation.reload();\n\t\t\t\t\t} catch {\n\t\t\t\t\t\tsetTimeout(waitForServer, 500);\n\t\t\t\t\t}\n\t\t\t\t};\n\n\t\t\t\tconst connect = () => {\n\t\t\t\t\tconst socket = new WebSocket(wsURL);\n\n\t\t\t\t\tsocket.onopen = () => {\n\t\t\t\t\t\tconnected = true;\n\t\t\t\t\t};\n\n\t\t\t\t\tsocket.onmessage = () => location.reload();\n\n\t\t\t\t\tsocket.onclose = () => {\n\t\t\t\t\t\tif (connected) {\n\t\t\t\t\t\t\tconnected = false;\n\t\t\t\t\t\t\twaitForServer();\n\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\tsetTimeout(connect, 500);\n\t\t\t\t\t\t}\n\t\t\t\t\t};\n\t\t\t\t};\n\n\t\t\t\tconnect();\n\t\t\t})();\n\t\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		}
		return nil
	})
}
var _ = templruntime.GeneratedTemplate